import { createServerFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";

const playerSchema=z.object({name:z.string().trim().min(2).max(80),jerseyNumber:z.number().int().min(0).max(99),position:z.enum(["GK","DEF","MID","FWD"]),isCaptain:z.boolean()});
const teamSchema=z.object({name:z.string().trim().min(2).max(60),shortName:z.string().trim().toUpperCase().regex(/^[A-Z0-9]{3}$/),kitColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/),players:z.array(playerSchema).min(5).max(18)});
const draftSchema=z.object({name:z.string().trim().min(2).max(80),venue:z.string().trim().min(2).max(120),startDate:z.string().date(),scorerPin:z.string().regex(/^\d{4}$/),teamSize:z.number().int().min(5).max(11),maxSubs:z.union([z.literal(3),z.literal(5),z.literal(7)]),halfMinutes:z.number().int().min(5).max(60),extraTimeEnabled:z.boolean(),extraTimeHalfMinutes:z.number().int().min(1).max(15),penaltiesEnabled:z.boolean(),format:z.enum(["round_robin","knockout","hybrid"]),roundRobinLegs:z.union([z.literal(1),z.literal(2)]),seeding:z.enum(["random","manual"]),groupCount:z.union([z.literal(1),z.literal(2)]),advanceCount:z.union([z.literal(2),z.literal(4)]),teams:z.array(teamSchema).min(4).max(10)}).superRefine((d,ctx)=>{d.teams.forEach((t,i)=>{if(t.players.length<d.teamSize||t.players.length>d.teamSize+7)ctx.addIssue({code:"custom",path:["teams",i,"players"],message:`Squad must have ${d.teamSize}–${d.teamSize+7} players`});if(t.players.filter(p=>p.position==="GK").length<1)ctx.addIssue({code:"custom",path:["teams",i,"players"],message:"Add at least one goalkeeper"});if(t.players.filter(p=>p.isCaptain).length!==1)ctx.addIssue({code:"custom",path:["teams",i,"players"],message:"Choose exactly one captain"});});});
const slugSchema=z.string().regex(/^[a-z0-9-]{6,40}$/);
function pub(){return createClient<Database>(process.env['SUPABASE_URL']!,process.env['SUPABASE_PUBLISHABLE_KEY']!,{auth:{persistSession:false,autoRefreshToken:false}})}
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
function safeEqual(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)}

export const getTournament=createServerFn({method:"GET"}).inputValidator((d)=>z.object({slug:slugSchema}).parse(d)).handler(async({data})=>{
 const db=pub(); const {data:t,error}=await db.from("tournaments").select("id,public_slug,name,venue,start_date,team_size,max_subs,half_minutes,extra_time_enabled,penalties_enabled,format").eq("public_slug",data.slug).maybeSingle(); if(error)throw new Error(error.message); if(!t)throw new Error("Tournament not found");
 const [teams,players,matches,events]=await Promise.all([db.from("teams").select("id,tournament_id,name,short_name,kit_color,seed,group_name").eq("tournament_id",t.id).order("seed"),db.from("players").select("id,tournament_id,team_id,name,jersey_number,position,is_captain").eq("tournament_id",t.id).order("jersey_number"),db.from("matches").select("id,tournament_id,home_team_id,away_team_id,round_label,round_number,scheduled_at,pitch,status,home_score,away_score,home_penalties,away_penalties,player_of_match_id").eq("tournament_id",t.id).order("scheduled_at"),db.from("match_events").select("id,match_id,team_id,player_id,related_player_id,event_type,minute,stoppage_minute,is_penalty,created_at").eq("tournament_id",t.id).order("created_at")]);
 for(const r of [teams,players,matches,events])if(r.error)throw new Error(r.error.message); return {tournament:t,teams:teams.data??[],players:players.data??[],matches:matches.data??[],events:events.data??[]};
});

function rounds(ids:string[],legs:number){const arr=[...ids];if(arr.length%2)arr.push("");const out:Array<[string,string,number]>=[];for(let r=0;r<arr.length-1;r++){for(let i=0;i<arr.length/2;i++){const a=arr[i],b=arr[arr.length-1-i];if(a&&b)out.push(r%2?[b,a,r+1]:[a,b,r+1]);}arr.splice(1,0,arr.pop()??"");}if(legs===2){const first=[...out];first.forEach(([a,b,r])=>out.push([b,a,r+arr.length-1]));}return out;}

export const createTournament=createServerFn({method:"POST"}).inputValidator((d)=>draftSchema.parse(d)).handler(async({data})=>{
 const token=randomBytes(32).toString("base64url"); const slug=randomBytes(7).toString("hex"); const {supabaseAdmin}=await import("@/integrations/supabase/client.server");
 const {data:t,error}=await supabaseAdmin.from("tournaments").insert({public_slug:slug,name:data.name,venue:data.venue,start_date:data.startDate,team_size:data.teamSize,max_subs:data.maxSubs,half_minutes:data.halfMinutes,extra_time_enabled:data.extraTimeEnabled,extra_time_half_minutes:data.extraTimeHalfMinutes,penalties_enabled:data.penaltiesEnabled,format:data.format,round_robin_legs:data.roundRobinLegs,seeding:data.seeding,group_count:data.groupCount,advance_count:data.advanceCount}).select("id,public_slug,name").single(); if(error)throw new Error(error.message);
 const {error:se}=await supabaseAdmin.from("tournament_secrets").insert({tournament_id:t.id,edit_token_hash:hash(token),scorer_pin_hash:hash(`${data.scorerPin}:${t.id}`)});if(se)throw new Error(se.message);
 const {data:teams,error:te}=await supabaseAdmin.from("teams").insert(data.teams.map((team,i)=>({tournament_id:t.id,name:team.name,short_name:team.shortName,kit_color:team.kitColor,seed:i+1,group_name:data.groupCount===2?(i%2?"Group B":"Group A"):null}))).select("id,seed");if(te)throw new Error(te.message);
 const bySeed=new Map((teams??[]).map(x=>[x.seed,x.id]));
 const playerRows=data.teams.flatMap((team,i)=>team.players.map(p=>({tournament_id:t.id,team_id:bySeed.get(i+1)??"",name:p.name,jersey_number:p.jerseyNumber,position:p.position,is_captain:p.isCaptain})));const {error:pe}=await supabaseAdmin.from("players").insert(playerRows);if(pe)throw new Error(pe.message);
 const ids=(teams??[]).sort((a,b)=>a.seed-b.seed).map(x=>x.id); const pairs=rounds(ids,data.roundRobinLegs); const base=new Date(`${data.startDate}T09:00:00Z`); const fixtures=pairs.map(([home,away,round],i)=>({tournament_id:t.id,home_team_id:home,away_team_id:away,round_number:round,round_label:`Matchday ${round}`,stage:data.format==="knockout"?"quarter_final":"league",scheduled_at:new Date(base.getTime()+i*60*60*1000).toISOString(),pitch:`Pitch ${(i%2)+1}`}));if(fixtures.length){const {error:me}=await supabaseAdmin.from("matches").insert(fixtures);if(me)throw new Error(me.message)}
 return {slug:t.public_slug,name:t.name,token};
});

const scoreSchema=z.object({matchId:z.string().uuid(),credential:z.string().min(4).max(200),kind:z.enum(["organiser","pin"]),teamId:z.string().uuid(),playerId:z.string().uuid().nullable(),eventType:z.enum(["goal","own_goal","yellow","red"]),minute:z.number().int().min(0).max(180)});
export const addMatchEvent=createServerFn({method:"POST"}).inputValidator((d)=>scoreSchema.parse(d)).handler(async({data})=>{
 const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:m}=await supabaseAdmin.from("matches").select("tournament_id").eq("id",data.matchId).single();if(!m)throw new Error("Match not found");const {data:s}=await supabaseAdmin.from("tournament_secrets").select("edit_token_hash,scorer_pin_hash").eq("tournament_id",m.tournament_id).single();if(!s)throw new Error("Access unavailable");const expected=data.kind==="organiser"?hash(data.credential):hash(`${data.credential}:${m.tournament_id}`);const stored=data.kind==="organiser"?s.edit_token_hash:s.scorer_pin_hash;if(!safeEqual(expected,stored))throw new Error("Incorrect organiser link or scorer PIN");const {error}=await supabaseAdmin.from("match_events").insert({tournament_id:m.tournament_id,match_id:data.matchId,team_id:data.teamId,player_id:data.playerId,event_type:data.eventType,minute:data.minute});if(error)throw new Error(error.message);if(data.eventType==="goal"||data.eventType==="own_goal"){const {data:match}=await supabaseAdmin.from("matches").select("home_team_id,home_score,away_score").eq("id",data.matchId).single();if(match){const scoringTeam=data.eventType==="own_goal"?(data.teamId===match.home_team_id?"away":"home"):(data.teamId===match.home_team_id?"home":"away");await supabaseAdmin.from("matches").update(scoringTeam==="home"?{home_score:match.home_score+1}:{away_score:match.away_score+1}).eq("id",data.matchId)}}return {ok:true};
});
