import { createServerFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";

const playerSchema = z.object({ name:z.string().trim().min(2).max(80), jerseyNumber:z.number().int().min(0).max(99), position:z.enum(["GK","DEF","MID","FWD"]), isCaptain:z.boolean() });
const teamSchema = z.object({ name:z.string().trim().min(2).max(60), shortName:z.string().trim().toUpperCase().regex(/^[A-Z0-9]{3}$/), kitColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/), players:z.array(playerSchema).min(5).max(18) });
const draftSchema = z.object({ name:z.string().trim().min(2).max(80), venue:z.string().trim().min(2).max(120), startDate:z.string().date(), scorerPin:z.string().regex(/^\d{4}$/), teamSize:z.number().int().min(5).max(11), maxSubs:z.union([z.literal(3),z.literal(5),z.literal(7)]), halfMinutes:z.number().int().min(5).max(60), extraTimeEnabled:z.boolean(), extraTimeHalfMinutes:z.number().int().min(1).max(15), penaltiesEnabled:z.boolean(), format:z.enum(["round_robin","knockout","hybrid"]), roundRobinLegs:z.union([z.literal(1),z.literal(2)]), seeding:z.enum(["random","manual"]), groupCount:z.union([z.literal(1),z.literal(2)]), advanceCount:z.union([z.literal(2),z.literal(4)]), teams:z.array(teamSchema).min(4).max(10) }).superRefine((d,ctx)=>d.teams.forEach((t,i)=>{if(t.players.length<d.teamSize||t.players.length>d.teamSize+7)ctx.addIssue({code:"custom",path:["teams",i,"players"],message:`Squad must have ${d.teamSize}–${d.teamSize+7} players`});if(!t.players.some(p=>p.position==="GK"))ctx.addIssue({code:"custom",path:["teams",i,"players"],message:"Add at least one goalkeeper"});if(t.players.filter(p=>p.isCaptain).length!==1)ctx.addIssue({code:"custom",path:["teams",i,"players"],message:"Choose exactly one captain"})}));
const slugSchema=z.string().regex(/^[a-z0-9-]{6,40}$/);
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const safeEqual=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
function publicClient(){return createClient<Database>(process.env['SUPABASE_URL']!,process.env['SUPABASE_PUBLISHABLE_KEY']!,{auth:{storage:undefined,persistSession:false,autoRefreshToken:false}})}

export const getTournament=createServerFn({method:"GET"}).inputValidator((d)=>z.object({slug:slugSchema}).parse(d)).handler(async({data})=>{
  const db=publicClient();
  const {data:t,error}=await db.from("tournaments").select("id,public_slug,name,venue,start_date,team_size,max_subs,half_minutes,extra_time_enabled,penalties_enabled,format").eq("public_slug",data.slug).maybeSingle();
  if(error)throw new Error(error.message);if(!t)throw new Error("Tournament not found");
  const [teams,players,matches,events,lineups,kicks]=await Promise.all([
    db.from("teams").select("id,tournament_id,name,short_name,kit_color,seed,group_name").eq("tournament_id",t.id).order("seed"),
    db.from("players").select("id,tournament_id,team_id,name,jersey_number,position,is_captain").eq("tournament_id",t.id).order("jersey_number"),
    db.from("matches").select("id,tournament_id,home_team_id,away_team_id,round_label,round_number,stage,scheduled_at,pitch,status,clock_started_at,clock_elapsed_seconds,clock_running,home_score,away_score,home_penalties,away_penalties,player_of_match_id,next_match_id,next_match_slot").eq("tournament_id",t.id).order("scheduled_at"),
    db.from("match_events").select("id,match_id,team_id,player_id,related_player_id,event_type,minute,stoppage_minute,is_penalty,created_at").eq("tournament_id",t.id).order("created_at"),
    db.from("lineups").select("id,match_id,team_id,player_id,role,is_goalkeeper").eq("tournament_id",t.id),
    db.from("shootout_kicks").select("id,match_id,team_id,player_id,kick_order,result").eq("tournament_id",t.id).order("kick_order")
  ]);
  for(const result of [teams,players,matches,events,lineups,kicks])if(result.error)throw new Error(result.error.message);
  return {tournament:t,teams:teams.data??[],players:players.data??[],matches:matches.data??[],events:events.data??[],lineups:lineups.data??[],kicks:kicks.data??[]};
});

function rounds(ids:string[],legs:number){const rotating=[...ids];if(rotating.length%2)rotating.push("");const out:Array<[string,string,number]>=[];for(let round=0;round<rotating.length-1;round++){for(let i=0;i<rotating.length/2;i++){const a=rotating[i],b=rotating[rotating.length-1-i];if(a&&b)out.push(round%2?[b,a,round+1]:[a,b,round+1]);}rotating.splice(1,0,rotating.pop()??"");}if(legs===2){const first=[...out];first.forEach(([a,b,r])=>out.push([b,a,r+rotating.length-1]));}return out;}
type Fixture={id?:string;tournament_id:string;home_team_id:string|null;away_team_id:string|null;round_number:number;round_label:string;stage:"league"|"group"|"round_of_16"|"quarter_final"|"semi_final"|"final";scheduled_at:string;pitch:string;next_match_id?:string|null;next_match_slot?:"home"|"away"|null};
function knockoutFixtures(tournamentId:string,ids:string[],base:Date,offset=0):Fixture[]{const size=2**Math.ceil(Math.log2(ids.length));const roundsCount=Math.log2(size);const all:Fixture[][]=[];for(let r=0;r<roundsCount;r++){const count=size/(2**(r+1));const stage=count===1?"final":count===2?"semi_final":count===4?"quarter_final":"round_of_16";all.push(Array.from({length:count},(_,i)=>({id:randomUUID(),tournament_id:tournamentId,home_team_id:r===0?(ids[i]??null):null,away_team_id:r===0?(ids[size-1-i]??null):null,round_number:r+1,round_label:stage.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()),stage,scheduled_at:new Date(base.getTime()+(offset+r*4+i)*3600000).toISOString(),pitch:`Pitch ${(i%2)+1}`})));}for(let r=0;r<all.length-1;r++)all[r].forEach((m,i)=>{m.next_match_id=all[r+1][Math.floor(i/2)]?.id??null;m.next_match_slot=i%2===0?"home":"away"});return all.flat();}

export const createTournament=createServerFn({method:"POST"}).inputValidator((d)=>draftSchema.parse(d)).handler(async({data})=>{
  const token=randomBytes(32).toString("base64url"),slug=randomBytes(7).toString("hex");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");
  const {data:t,error}=await supabaseAdmin.from("tournaments").insert({public_slug:slug,name:data.name,venue:data.venue,start_date:data.startDate,team_size:data.teamSize,max_subs:data.maxSubs,half_minutes:data.halfMinutes,extra_time_enabled:data.extraTimeEnabled,extra_time_half_minutes:data.extraTimeHalfMinutes,penalties_enabled:data.penaltiesEnabled,format:data.format,round_robin_legs:data.roundRobinLegs,seeding:data.seeding,group_count:data.groupCount,advance_count:data.advanceCount}).select("id,public_slug,name").single();if(error)throw new Error(error.message);
  const {error:secretError}=await supabaseAdmin.from("tournament_secrets").insert({tournament_id:t.id,edit_token_hash:hash(token),scorer_pin_hash:hash(`${data.scorerPin}:${t.id}`)});if(secretError)throw new Error(secretError.message);
  const {data:teams,error:teamError}=await supabaseAdmin.from("teams").insert(data.teams.map((team,i)=>({tournament_id:t.id,name:team.name,short_name:team.shortName,kit_color:team.kitColor,seed:i+1,group_name:data.format==="hybrid"&&data.groupCount===2?(i%2?"Group B":"Group A"):null}))).select("id,seed,group_name");if(teamError)throw new Error(teamError.message);
  const bySeed=new Map((teams??[]).map(team=>[team.seed,team.id]));const playerRows=data.teams.flatMap((team,i)=>team.players.map(player=>({tournament_id:t.id,team_id:bySeed.get(i+1)??"",name:player.name,jersey_number:player.jerseyNumber,position:player.position,is_captain:player.isCaptain})));const {error:playerError}=await supabaseAdmin.from("players").insert(playerRows);if(playerError)throw new Error(playerError.message);
  const sorted=(teams??[]).sort((a,b)=>a.seed-b.seed),ids=sorted.map(team=>team.id),base=new Date(`${data.startDate}T09:00:00Z`);let fixtures:Fixture[]=[];
  if(data.format==="knockout")fixtures=knockoutFixtures(t.id,ids,base);
  else {const groups=data.format==="hybrid"&&data.groupCount===2?[sorted.filter(t=>t.group_name==="Group A"),sorted.filter(t=>t.group_name==="Group B")]:[sorted];let index=0;for(const group of groups){for(const [home,away,round] of rounds(group.map(t=>t.id),data.roundRobinLegs)){fixtures.push({tournament_id:t.id,home_team_id:home,away_team_id:away,round_number:round,round_label:groups.length===2?`${group[0]?.group_name} · Matchday ${round}`:`Matchday ${round}`,stage:groups.length===2?"group":"league",scheduled_at:new Date(base.getTime()+index++*3600000).toISOString(),pitch:`Pitch ${(index%2)+1}`});}}if(data.format==="hybrid")fixtures.push(...knockoutFixtures(t.id,Array.from({length:data.advanceCount},()=>""),base,index+2));}
  if(fixtures.length){const {error:matchError}=await supabaseAdmin.from("matches").insert(fixtures);if(matchError)throw new Error(matchError.message)}return {slug:t.public_slug,name:t.name,token};
});

async function verifyCredential(tournamentId:string,credential:string,kind:"organiser"|"session",admin:any){const {data:secret}=await admin.from("tournament_secrets").select("edit_token_hash").eq("tournament_id",tournamentId).single();if(kind==="organiser")return !!secret&&safeEqual(hash(credential),secret.edit_token_hash);const {data:session}=await admin.from("scorer_sessions").select("id").eq("tournament_id",tournamentId).eq("token_hash",hash(credential)).gt("expires_at",new Date().toISOString()).maybeSingle();return !!session;}
export const unlockScoring=createServerFn({method:"POST"}).inputValidator((d)=>z.object({matchId:z.string().uuid(),pin:z.string().regex(/^\d{4}$/)}).parse(d)).handler(async({data})=>{const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:match}=await supabaseAdmin.from("matches").select("tournament_id").eq("id",data.matchId).single();if(!match)throw new Error("Match not found");const attemptKey=hash(`${match.tournament_id}:scorer`);const since=new Date(Date.now()-15*60000).toISOString();const {count}=await supabaseAdmin.from("pin_attempts").select("id",{count:"exact",head:true}).eq("tournament_id",match.tournament_id).eq("attempt_key",attemptKey).eq("succeeded",false).gte("attempted_at",since);if((count??0)>=5)throw new Error("Too many incorrect attempts. Try again in 15 minutes.");const {data:secret}=await supabaseAdmin.from("tournament_secrets").select("scorer_pin_hash").eq("tournament_id",match.tournament_id).single();const valid=!!secret&&safeEqual(hash(`${data.pin}:${match.tournament_id}`),secret.scorer_pin_hash);await supabaseAdmin.from("pin_attempts").insert({tournament_id:match.tournament_id,attempt_key:attemptKey,succeeded:valid});if(!valid)throw new Error("Incorrect scorer PIN");const token=randomBytes(32).toString("base64url");const {error}=await supabaseAdmin.from("scorer_sessions").insert({tournament_id:match.tournament_id,token_hash:hash(token),expires_at:new Date(Date.now()+12*3600000).toISOString()});if(error)throw new Error(error.message);return {token};});
const credentialSchema=z.object({matchId:z.string().uuid(),credential:z.string().min(20).max(200),kind:z.enum(["organiser","session"])});
const scoreSchema=credentialSchema.extend({teamId:z.string().uuid(),playerId:z.string().uuid().nullable(),relatedPlayerId:z.string().uuid().nullable().optional(),eventType:z.enum(["goal","own_goal","yellow","red","second_yellow","substitution"]),minute:z.number().int().min(0).max(180),isPenalty:z.boolean().optional()});
export const addMatchEvent=createServerFn({method:"POST"}).inputValidator((d)=>scoreSchema.parse(d)).handler(async({data})=>{const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:match}=await supabaseAdmin.from("matches").select("tournament_id,home_team_id,away_team_id,home_score,away_score").eq("id",data.matchId).single();if(!match)throw new Error("Match not found");if(data.teamId!==match.home_team_id&&data.teamId!==match.away_team_id)throw new Error("That team is not in this match");if(!await verifyCredential(match.tournament_id,data.credential,data.kind,supabaseAdmin))throw new Error("Scoring access expired or invalid");let eventType=data.eventType;if(eventType==="yellow"&&data.playerId){const {count}=await supabaseAdmin.from("match_events").select("id",{count:"exact",head:true}).eq("match_id",data.matchId).eq("player_id",data.playerId).in("event_type",["yellow","second_yellow"]);if((count??0)>0)eventType="second_yellow";}const {error}=await supabaseAdmin.from("match_events").insert({tournament_id:match.tournament_id,match_id:data.matchId,team_id:data.teamId,player_id:data.playerId,related_player_id:data.relatedPlayerId??null,event_type:eventType,minute:data.minute,is_penalty:data.isPenalty??false});if(error)throw new Error(error.message);if(eventType==="goal"||eventType==="own_goal"){const teamIsHome=data.teamId===match.home_team_id;const homeScores=eventType==="own_goal"?!teamIsHome:teamIsHome;const {error:updateError}=await supabaseAdmin.from("matches").update(homeScores?{home_score:match.home_score+1}:{away_score:match.away_score+1}).eq("id",data.matchId);if(updateError)throw new Error(updateError.message)}return {ok:true};});
export const controlMatch=createServerFn({method:"POST"}).inputValidator((d)=>credentialSchema.extend({action:z.enum(["start_first","half_time","start_second","pause","full_time","undo"]),elapsedSeconds:z.number().int().min(0).max(10800).optional()}).parse(d)).handler(async({data})=>{const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:match}=await supabaseAdmin.from("matches").select("tournament_id,status,clock_elapsed_seconds,clock_started_at,home_team_id,away_team_id").eq("id",data.matchId).single();if(!match)throw new Error("Match not found");if(!await verifyCredential(match.tournament_id,data.credential,data.kind,supabaseAdmin))throw new Error("Scoring access expired or invalid");if(data.action==="undo"){const {data:event}=await supabaseAdmin.from("match_events").select("id,event_type,team_id").eq("match_id",data.matchId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(event){await supabaseAdmin.from("match_events").delete().eq("id",event.id);if(event.event_type==="goal"||event.event_type==="own_goal"){const {data:current}=await supabaseAdmin.from("matches").select("home_score,away_score").eq("id",data.matchId).single();if(current){const teamIsHome=event.team_id===match.home_team_id,homeScored=event.event_type==="own_goal"?!teamIsHome:teamIsHome;await supabaseAdmin.from("matches").update(homeScored?{home_score:Math.max(0,current.home_score-1)}:{away_score:Math.max(0,current.away_score-1)}).eq("id",data.matchId)}}}return {ok:true};}const now=new Date().toISOString();const elapsed=data.elapsedSeconds??match.clock_elapsed_seconds;const patch=data.action==="start_first"?{status:"first_half",clock_running:true,clock_started_at:now,clock_elapsed_seconds:0}:data.action==="half_time"?{status:"half_time",clock_running:false,clock_started_at:null,clock_elapsed_seconds:elapsed}:data.action==="start_second"?{status:"second_half",clock_running:true,clock_started_at:now,clock_elapsed_seconds:elapsed}:data.action==="pause"?{clock_running:false,clock_started_at:null,clock_elapsed_seconds:elapsed}:{status:"full_time",clock_running:false,clock_started_at:null,clock_elapsed_seconds:elapsed};const {error}=await supabaseAdmin.from("matches").update(patch).eq("id",data.matchId);if(error)throw new Error(error.message);return {ok:true};});
