import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, Radio, ShieldCheck, Trophy, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell, SectionTitle } from "@/components/kickoff/app-shell";
import { Button } from "@/components/ui/button";
import { getRemembered, type RememberedTournament } from "@/lib/kickoff";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Kickoff — Run your tournament"},{name:"description",content:"Create, score and share amateur football tournaments live."},{property:"og:title",content:"Kickoff — Run your tournament"},{property:"og:description",content:"Create, score and share amateur football tournaments live."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Home});
function Home(){const [mine,setMine]=useState<RememberedTournament[]>([]);useEffect(()=>setMine(getRemembered()),[]);return <AppShell><section className="border-b border-border"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-14 md:grid-cols-[1.2fr_.8fr] md:py-24"><div><div className="mb-6 inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-primary"><Radio className="size-4"/>Live tournament control</div><h1 className="max-w-3xl text-5xl font-black leading-[.95] sm:text-7xl">YOUR TOURNAMENT.<br/><span className="text-primary">ONE LINK.</span></h1><p className="mt-6 max-w-xl text-lg text-muted-foreground">Fixtures, live scores, tables and player stats for the football you actually play. No accounts. No clutter.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/create"><PlusIcon/>Create tournament</Link></Button><Button size="lg" variant="outline" asChild><Link to="/t/$slug" params={{slug:"campus-cup-26"}}>Explore demo <ArrowRight/></Link></Button></div><div className="mt-10 flex flex-wrap gap-5 text-sm text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary"/>No sign-up</span><span className="flex items-center gap-2"><Radio className="size-4 text-primary"/>Live updates</span><span className="flex items-center gap-2"><Users className="size-4 text-primary"/>4–10 teams</span></div></div><div className="scoreboard"><p className="scoreboard-label">Campus Cup · FT</p><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-5"><TeamMark code="FAL" color="bg-team-coral"/><strong className="text-6xl font-black">2<span className="mx-3 text-muted-foreground">–</span>1</strong><TeamMark code="ROV" color="bg-team-green"/></div><div className="mt-6 border-t border-border pt-4 text-center text-sm text-muted-foreground">Owen Price 8′, 31′ · Luke Hall 14′</div></div></div></section><section className="mx-auto max-w-6xl px-4 py-12"><SectionTitle eyebrow="On this device" title="My tournaments" action={<Button variant="ghost" asChild><Link to="/create">New <ArrowRight/></Link></Button>}/>{mine.length?<div className="grid gap-3 md:grid-cols-2">{mine.map(t=><Link key={t.slug} to="/t/$slug" params={{slug:t.slug}} className="match-card"><Trophy className="size-5 text-primary"/><div className="flex-1"><strong>{t.name}</strong><p className="text-xs text-muted-foreground">Opened {new Date(t.openedAt).toLocaleDateString()}</p></div><ArrowRight className="size-5"/></Link>)}</div>:<Link to="/t/$slug" params={{slug:"campus-cup-26"}} className="match-card"><div className="grid size-11 place-items-center rounded-md bg-secondary"><CalendarDays className="size-5 text-primary"/></div><div className="flex-1"><strong>Campus Cup 2026</strong><p className="text-sm text-muted-foreground">Demo tournament · 4 teams</p></div><ArrowRight className="size-5"/></Link>}</section></AppShell>}
function TeamMark({code,color}:{code:string;color:string}){return <div className="text-center"><span className={`mx-auto mb-2 block size-14 rounded-full border-4 border-card ${color}`}/><b>{code}</b></div>};function PlusIcon(){return <span className="text-xl leading-none">+</span>}
