import { Link } from "@tanstack/react-router";
import { Calendar, ChevronRight, Copy, Download, MapPin, Medal, Radio, Share2, Shield, Star, Trophy, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "./app-shell";
import { Button } from "@/components/ui/button";
import { playerFor, shareOrigin, playerStats, rememberTournament, standings, statusLabel, teamFor, type PublicTournament } from "@/lib/kickoff";
import { supabase } from "@/integrations/supabase/client";

export function TournamentView({data,organiserToken}:{data:PublicTournament;organiserToken?:string}){const [tab,setTab]=useState("matches");const t=data.tournament;useEffect(()=>{rememberTournament({slug:t.public_slug,name:t.name,...(organiserToken?{organiserUrl:`${shareOrigin()}/t/${t.public_slug}/manage?token=${encodeURIComponent(organiserToken)}`} : {}),openedAt:new Date().toISOString()})},[t.public_slug,t.name,organiserToken]);useEffect(()=>{const c=supabase.channel(`t-${t.id}`).on("postgres_changes",{event:"*",schema:"public",table:"matches",filter:`tournament_id=eq.${t.id}`},()=>location.reload()).on("postgres_changes",{event:"*",schema:"public",table:"match_events",filter:`tournament_id=eq.${t.id}`},()=>location.reload()).subscribe();return()=>{void supabase.removeChannel(c)}},[t.id]);const tabs=["matches",...(t.format!=="knockout"?["table"]:[]),...(t.format!=="round_robin"?["bracket"]:[]),"stats","teams"];
 const share=async()=>{const url=`${shareOrigin()}/t/${t.public_slug}`;await navigator.clipboard.writeText(url);toast.success("Public link copied");window.open(`https://wa.me/?text=${encodeURIComponent(`${t.name} — fixtures and live scores: ${url}`)}`,"_blank")};
 return <AppShell><section className="tournament-banner"><div className="mx-auto max-w-6xl px-4 py-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-widest text-primary"><Trophy className="size-4"/>{t.format.replaceAll("_"," ")}</p><h1 className="text-4xl font-black sm:text-5xl">{t.name}</h1><div className="mt-3 flex flex-wrap gap-4 text-sm text-muted-foreground"><span className="flex gap-2"><MapPin className="size-4"/>{t.venue}</span><span className="flex gap-2"><Calendar className="size-4"/>{new Date(`${t.start_date}T12:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"long",year:"numeric"})}</span></div></div><div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Share tournament" onClick={share}><Share2/></Button>{organiserToken&&<Button asChild><Link to="/t/$slug/manage" params={{slug:t.public_slug}} search={{token:organiserToken}}><Shield/>Manage</Link></Button>}</div></div><div className="mt-8 flex gap-1 overflow-x-auto">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`tab-button ${tab===x?"active":""}`}>{x}</button>)}</div></div></section><div className="mx-auto max-w-6xl px-4 py-8">{tab==="matches"&&<Matches data={data}/>} {tab==="table"&&<Table data={data}/>} {tab==="bracket"&&<Bracket data={data}/>} {tab==="stats"&&<Stats data={data}/>} {tab==="teams"&&<Teams data={data}/>}</div></AppShell>}
function Matches({data}:{data:PublicTournament}){const groups=[...data.matches].sort((a,b)=>(a.status.includes("half")?-1:0)-(b.status.includes("half")?-1:0)).reduce<Record<string,PublicTournament["matches"]>>((all,m)=>{(all[m.round_label]??=[]).push(m);return all},{});return <div className="grid gap-8">{Object.entries(groups).map(([round,matches])=><section key={round}><h2 className="mb-3 text-xs font-black uppercase tracking-widest text-muted-foreground">{round}</h2><div className="grid gap-2">{matches?.map(m=><Link key={m.id} to="/t/$slug/match/$matchId" params={{slug:data.tournament.public_slug,matchId:m.id}} search={{token:""}} className="match-card"><div className="w-16 text-xs text-muted-foreground">{new Date(m.scheduled_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}<br/>{m.pitch}</div><div className="min-w-0 flex-1"><TeamRow data={data} id={m.home_team_id} score={m.status==="scheduled"?undefined:m.home_score}/><TeamRow data={data} id={m.away_team_id} score={m.status==="scheduled"?undefined:m.away_score}/></div><span className={m.status.includes("half")?"live-badge":"status-badge"}>{statusLabel(m.status)}</span><ChevronRight className="size-4 text-muted-foreground"/></Link>)}</div></section>)}</div>}
function TeamRow({data,id,score}:{data:PublicTournament;id:string|null;score:number|undefined}){const t=teamFor(data,id);return <div className="flex items-center gap-2 py-1 text-sm font-bold"><span className="size-3 rounded-full border border-border" style={{backgroundColor:t?.kit_color}}/><span className="truncate">{t?.name??"TBD"}</span>{score!==undefined&&<b className="ml-auto text-lg">{score}</b>}</div>}
function Table({data}:{data:PublicTournament}){return <div className="overflow-hidden rounded-lg border border-border"><table className="w-full text-sm"><thead><tr className="bg-secondary text-left text-xs uppercase text-muted-foreground"><th className="p-3"># Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th className="pr-3 text-right">Pts</th></tr></thead><tbody>{standings(data).map((r,i)=><tr key={r.team.id} className="border-t border-border"><td className="p-3 font-bold"><span className="mr-3 text-muted-foreground">{i+1}</span><span className="mr-2 inline-block size-2 rounded-full" style={{backgroundColor:r.team.kit_color}}/>{r.team.short_name}</td><td>{r.p}</td><td>{r.w}</td><td>{r.d}</td><td>{r.l}</td><td>{r.gd}</td><td className="pr-3 text-right font-black">{r.pts}</td></tr>)}</tbody></table></div>}
function Bracket({data}:{data:PublicTournament}){const first=data.matches[0];const final=first?[{...first,home_team_id:null,away_team_id:null,status:"scheduled",home_score:0,away_score:0,id:"final-placeholder"}]:[];return <div className="overflow-x-auto pb-4"><div className="grid min-w-[680px] grid-cols-3 gap-8"><BracketRound title="Semi-finals" matches={data.matches.slice(0,2)} data={data}/><div className="pt-20"><BracketRound title="Final" matches={final} data={data}/></div><div className="grid place-items-center"><div className="text-center"><Trophy className="mx-auto size-14 text-primary"/><p className="mt-3 text-xs font-black uppercase text-muted-foreground">Champion</p><h3 className="text-xl font-black">To be decided</h3></div></div></div></div>}
function BracketRound({title,matches,data}:{title:string;matches:PublicTournament["matches"];data:PublicTournament}){return <div><p className="mb-3 text-xs font-black uppercase text-muted-foreground">{title}</p>{matches.map(m=><div className="mb-3 rounded-md border border-border bg-card p-3" key={m.id}><TeamRow data={data} id={m.home_team_id} score={m.home_score}/><TeamRow data={data} id={m.away_team_id} score={m.away_score}/></div>)}</div>}
function Stats({data}:{data:PublicTournament}){const stats=playerStats(data);const boards=[{title:"Top scorers",icon:Trophy,rows:[...stats].sort((a,b)=>b.goals-a.goals),value:(x:typeof stats[number])=>x.goals,label:"goals"},{title:"Top assists",icon:Star,rows:[...stats].sort((a,b)=>b.assists-a.assists),value:(x:typeof stats[number])=>x.assists,label:"assists"},{title:"Cards",icon:Medal,rows:[...stats].sort((a,b)=>(b.yellow+b.red)-(a.yellow+a.red)),value:(x:typeof stats[number])=>x.yellow+x.red,label:"cards"}];return <div className="grid gap-4 md:grid-cols-3">{boards.map(b=><section className="stat-board" key={b.title}><h3><b.icon className="size-4 text-primary"/>{b.title}</h3>{b.rows.slice(0,5).map((s,i)=><Link to="/t/$slug/player/$playerId" params={{slug:data.tournament.public_slug,playerId:s.player.id}} key={s.player.id} className="stat-row"><b>{i+1}</b><div className="flex-1"><strong>{s.player.name}</strong><small>{teamFor(data,s.player.team_id)?.short_name}</small></div><strong>{b.value(s)} <small>{b.label}</small></strong></Link>)}</section>)}</div>}
function Teams({data}:{data:PublicTournament}){return <div className="grid gap-3 sm:grid-cols-2">{data.teams.map(t=><Link to="/t/$slug/team/$teamId" params={{slug:data.tournament.public_slug,teamId:t.id}} key={t.id} className="team-card"><span className="size-12 rounded-full border-4 border-card shadow" style={{backgroundColor:t.kit_color}}/><div className="flex-1"><h3>{t.name}</h3><p>{data.players.filter(p=>p.team_id===t.id).length} players · Seed {t.seed}</p></div><ChevronRight/></Link>)}</div>}
export function CopyButton({text,label="Copy"}:{text:string;label?:string}){return <Button variant="outline" onClick={async()=>{await navigator.clipboard.writeText(text);toast.success(`${label} copied`)}}><Copy/>{label}</Button>}
export function ExportButton({data}:{data:PublicTournament}){const download=()=>{const rows=[["Player","Team","Goals","Assists","Yellow","Red","POTM"],...playerStats(data).map(s=>[s.player.name,teamFor(data,s.player.team_id)?.name??"",s.goals,s.assists,s.yellow,s.red,s.potm])];const blob=new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${data.tournament.public_slug}-stats.csv`;a.click();URL.revokeObjectURL(a.href)};return <Button variant="outline" onClick={download}><Download/>Export CSV</Button>}
